### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by muzena** [linuxmint/live-installer#101]
@clefebvre 
Hi.
Is in this line, in translation:
"ERROR: the use of @subvolumes is limited to btrfs"
@subvolumes - Is this translatable or it should stay untranslated?

**Comment by monsta** [comment]
@orcus-de: can you please give some hints? :slightly_smiling_face:

**Comment by orcus-de** [comment]
sorry for the delay..
hmmm...  the terms @subvolume  @subvolumes don't even exist and has been my creation at that time and could be replaced with ...

>>ERROR: the use of /@ and /@home is limited to btrfs-subvolumes<<

**Comment by monsta** [comment]
I think the translatable strings won't be changed at this point - LMDE 4 is very close to the final release...

**Comment by orcus-de** [comment]
It's either way ok for me - so stick to @subvolumes

**Comment by muzena** [comment]
Ok, thanks @orcus-de 
I will change translation back to @subvolumes.
