### ISSUE TITLE
problem when installation uses grml

### ISSUE THREAD

**Issue by Wahyu6070** [linuxmint/live-installer#102]
I have spent a Linux mint without USB / CD, and has followed the Linux Mint Guide 
https://www.google.com/amp/s/mintguide.org/tools/881-install-linux-without-a-dvd-or-flash-drive.html/amp.
advice by using the GRML and entering the ISO file to /boot/grml but a problem and stuck loading in the installation.i using linux mint 19.3 mate

**Comment by clefebvre** [comment]
Sorry this is off-topic here, live-installer is the LMDE installer.
