### ISSUE TITLE
The installer starts with an IP-based language instead of English

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/live-installer#103]
I booted the final release of the 32-bit LMDE4 ISO in a VirtualBox session. When I started the installer, it was displayed in the German language. I tried forcing the locale to English by prefixing LANG, LC_ALL and LANGUAGE to the live-installer command from the terminal but the installer still started in German.

So I clicked "weiter" _(Next)_ and once I chose English US in the installer's language list, it switched the display language to English. Then I closed the installer, to see if it would remember my language of choice, but after I restarted the installer it was again in German.

So I closed the installer, disabled the network and restarted the installer. This time it was in English. This means it detects the country and it automatically starts in the local language. But this is not great because you might as well travel anywhere around the world, or maybe the IP is not correctly associated with the real country, and you don't know that country's language.

The installer should start in English. But if it tries to be smart about detecting the country, it could present a language switcher on the first screen of the installer, so you never have to guess which button says what for exit/back/next in any language.

Also, after I filled my user data and I started the installation process, I noticed a German text displayed on the bottom of the installer (the status area), although it went away quickly because that operation was fast. So I'm not sure what kind of effects the installer has on the final installation, but the locale is not properly handled for the installer's startup and then the installation process - to say the least.

Is there an installation log that I could inspect, to see if what was handled in German during the installation?

**Comment by clefebvre** [comment]
It uses geoip to preselect your locale, that's by design indeed.
