### ISSUE TITLE
LMDE 4: System frozen when installing GRUB

### ISSUE THREAD

**Issue by crigoda** [linuxmint/live-installer#105]
Hi,

During LDME 4 installation, my system froze when installing grub-efi-amd64:

(Sorry for the quality of the image)

![lmde4_frozen](https://user-images.githubusercontent.com/12408378/77930582-59d00300-72ab-11ea-98cd-ea551cbed918.png)

I already had this type of probem with my hardware (Acer Spin 1), so I'm using rEFInd as bootloader and to solve this problem, I added a "--no-bootloader" option to the installer to disable the installlation of the EFI bootloader.

I made this patch:
[nobootloader.zip](https://github.com/linuxmint/live-installer/files/4403800/nobootloader.zip)

I hope this can be useful for you.

**Comment by crigoda** [comment]
Pull request has been closed so can you close this issue and publish a fixed version of the install media ?

**Comment by clefebvre** [comment]
Just checked the code. This was fixed on master.
