### ISSUE TITLE
Installation without formating already formatted BTRFS partition.

### ISSUE THREAD

**Issue by thunderamur** [linuxmint/live-installer#110]
I try to install LMDE4 to already formatted Btrfs partition with compression=lzo property. Usually, in Linux Mint (Ubuntu), I format partition before installation and set compression to Btrfs filesystem. But here I can not do this. Installer warning me that I must indicate a filesystem to formate the root (/) partition with before proceeding. Installation continues only if I set format partition. 
![изображение](https://user-images.githubusercontent.com/5599470/81082006-a0112580-8f2d-11ea-9ac4-917368dc5484.png)
![изображение](https://user-images.githubusercontent.com/5599470/81082057-b15a3200-8f2d-11ea-8248-c51835a87664.png)

Please, make possible to install LMDE without formating already formatted BTRFS partition.

**Comment by clefebvre** [comment]
Even if you bypassed the format operation you'd still need to specify the compression somehow during the mount and in the fstab.

This is too niche a feature to be included in the installer. That said there are two options:

- Enabling compression and recompressing / post-installation: https://askubuntu.com/questions/129063/will-btrfs-automatically-compress-existing-files-when-compression-is-enabled
- Using the expert mode with `sudo live-installer --expert-mode`.
