### ISSUE TITLE
LVM Not detected

### ISSUE THREAD

**Issue by aaaaadrien** [linuxmint/live-installer#115]
Hello,
I created on the disk some LV, to prepare the installation of LMDE4
But when i am on "manual partition" the tool don't detect Logical volumes. it detects the PV as unknown partition and i can't install LMDE4 on my own Logical Volumes created before !

**Comment by pavinjosdev** [comment]
If anyone stumbles on this in the future, the solution is to use expert mode installation by invoking `/usr/bin/live-installer-expert-mode` from the terminal. This gives you a lot of control over where to install LMDE.
