### ISSUE TITLE
Do Latin characters contain numbers?

### ISSUE THREAD

**Issue by vegam57** [linuxmint/live-installer#121]
Do Latin characters contain numbers?
I'm worried about the description. 
![スクリーンショット 2022-02-03 13-54-21](https://user-images.githubusercontent.com/78515193/152284251-affe25b2-9bdd-407c-be15-712915a5efb2.png)

**Comment by clefebvre** [comment]
Yes

**Comment by vegam57** [comment]
Thank you.
In my translation, I try to translate based on the meaning that it can consist of Latin characters and numbers.
