### ISSUE TITLE
Code for LUKS available

### ISSUE THREAD

**Issue by harlekin777** [linuxmint/live-installer#122]
Dear Clem,
I noticed, you closed the previous requests regarding LUKS. As you also wrote, PRs are welcome. Unfortunately, I am not a developer. But I found a script on Github which contains all the necessary code and might be helpful for adding this feature: 
https://github.com/pepa65/lmdescrypt . 
Using this code would significantly reduce the work. Would you be so kind and reconsider including encryption into the LMDE 5 installer? It is a standard feature now in most distros. I am sure, many people would be very grateful to have it in LMDE as well.
Thank you for your great work.

**Comment by clefebvre** [comment]
Hi @harlekin777 it would require a UI redesign, it's not just a few lines of code. We're not doing it for LMDE 5.

We have LUKS support for the entire drive, but we're not planning to implement it separately for each partition.
