### ISSUE TITLE
Calamares advantages

### ISSUE THREAD

**Issue by harlekin777** [linuxmint/live-installer#123]
Dear Clem,
I am very sorry to bother you again. I understand, you do not want to add encryption to the live-installer for LMDE 5. Probably it is a burden for a side project such as LMDE. Is it not better then just to use Calamares? I would imagine, it has advantages for you and for the users as well. Calamares has encryption and all other necessary features and performs well in Debian live and many other distributions; and as it is maintained and developed outside, it would also reduce your workload.
Best regards, harlekin777

**Comment by clefebvre** [comment]
We'd need to adapt to it, live-installer is our own tool which we know very well.

Also it doesn't yet support home drive encryption which is quite important.
