### ISSUE TITLE
Keyboard layout switching

### ISSUE THREAD

**Issue by jtsagata** [linuxmint/live-installer#23]
If on the first screen you select the Greek language then the keyboard is switch into greek mode. The usual alt-Shift cομβο το switch language is not working. You can type only Greek characters, and there is no way to type in Latin. So computer name, user name and password is on Greek.
Not sure if this affects other languages.

If you setup the keyboard manually outside the installer then when the system start again you have again only  the Greek keyboard layout making the system unusable.

The expected behaviour:
When the user selects the Greek language the keyboard must be set to allow changing keyboard layouts with Alt-Shift, with the latin keyboard active. After setup the login manager must be on latin keyboard with the ability to switch to Greek.

**Comment by clefebvre** [comment]
Fixed in LMDE 3.
