### ISSUE TITLE
Drive Names and Partition Labels

### ISSUE THREAD

**Issue by philipzae** [linuxmint/live-installer#26]
I feel that it would be useful if partition labels can be included in the partitioning and grub part of the installer, similar to gparted.
![lmde installer - no partition lables](https://f.cloud.github.com/assets/4412114/2491576/512d4210-b1f2-11e3-8cf3-8c06416f747f.png)
![lmde installer - gparted](https://f.cloud.github.com/assets/4412114/2491583/81150436-b1f2-11e3-948d-a793ad7a436a.png)

In the grub part of the installer, drive names and partition labels would be quite useful. It might be useful to also have separate drop down menus for installing the bootloader to a drive or partition.
![lmde installer - no drive names or partition labels](https://f.cloud.github.com/assets/4412114/2491575/512a1874-b1f2-11e3-96ea-a3971edd5029.png)

**Comment by kneekoo** [comment]
The labels would be a quite welcome improvement, and it would be best if only the supported partitions would be offered as choices.

So the list could be changed like this:
```
/dev/sda
/dev/sdb
/dev/sda1 (DEBIAN)
/dev/sda2 **<- extended, don't list it**
/dev/sda3 (SOLYDX)
/dev/sda4 (LMDE)
/dev/sda5 **<- linux-swap, don't list it**
/dev/sda6 (PART4)
/dev/sda7 (PART5)
/dev/sda8 (PART6)
/dev/sda9 (HOME)
/dev/sdb1 (DATA)
```
