### ISSUE TITLE
Partition Guide (PDF / HTML page)

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/live-installer#64]
http://community.linuxmint.com/idea/view/398 This idea pretty much explains it. I believe, this is essential especially for dual-boot users. I follow forums quite regularly and you can see new users struggling to understand partition on Linux.

I would love to see this implemented soon. :smile: Thanks.

My personal story - 
When I switched from Windows, I had to go through various pages / sites to get a hold on the concepts. fdisk, /devsda, ext4, swap, etc. All these were completely new concepts and fortunately landed up on the [this tutorial](http://www.linuxbsdos.com/2011/06/11/dual-boot-linux-mint-11-and-windows-7/) and suggested to many newcomers in forums.

**Comment by NikoKrause** [comment]
There exists a Linux Mint Installation guide now.
