### ISSUE TITLE
installer wrote bootloader to the wrong disk

### ISSUE THREAD

**Issue by cjlee112** [linuxmint/live-installer#71]
Reported by two separate users on LM17 and LM17.1, one using installer DVD, the other installing from a USB key.  Full details of our reports here:
http://forums.linuxmint.com/viewtopic.php?f=46&t=189595

To summarize, on a multi-disk system, user chose to install Mint on /dev/sdc, but the installer ran `grub-install /dev/sda` (despite having correctly installed Mint OS files on /dev/sdc).  As a result, attempting to boot /dev/sdc will fail (because no bootloader was installed on this disk), and attempting to boot /dev/sda will ACTUALLY boot the fresh Mint install on /dev/sdc (because the bootloader on /dev/sda actually boots the OS from /dev/sdc)!  This makes the user think that the Mint installer erased /dev/sda and put a fresh Mint install on /dev/sda (which is NOT the case).  This could lead to catastrophic data loss.

Both of the reported cases involved LUKS + LVM installs; not sure if that is an important factor.

**Comment by monsta** [comment]
This is the installer for Linux Mint Debian Edition (LMDE). Mint 17.x installer is at https://github.com/linuxmint/ubiquity

**Comment by cjlee112** [comment]
yikes, my apologies for filing this in the wrong place!!! I'm afraid I went by the name "live-installer"; I didn't realize "ubiquity" was the name for the Mint 17.x installer.  My bad!!
