### ISSUE TITLE
Can't get the installer to boot on my machine

### ISSUE THREAD

**Issue by synhershko** [linuxmint/live-installer#72]
I have no idea where to even start diagnozing this

Downloaded the installer for the Cinnamon flavor , burned to disc, booted, and after loading for a while the installer I'm left with a blank screen

Let me know what info I can provide to help diagnose this

**Comment by kernc** [comment]
By _installer_, are you referring to the whole installation DVD image, which doesn't seem to boot correctly, or to the particular piece of software that has an icon sitting on the desktop and by which you install the live system onto the hard disk?

**Comment by synhershko** [comment]
The whole installation DVD image, it boots to a black screen. I see the Mint logo with "booting in X seconds..." message, then the Mint logo alone, then some noise from the CD drive, my web cam flashes, then screen blackens out and after a while everything is made quite....

**Comment by somian** [comment]
>
> The whole installation DVD image, it boots to a black screen. I see the
> Mint logo with "booting in X seconds..." message, then the Mint logo alone,
> then some noise from the CD drive, my web cam flashes, then screen blackens
> out and after a while everything is made quite ...


Hi.  Well this is not particularly likely to help, but:

One occasional cause of boot failures is display switch problems.  On
laptops the internal display 'card' (hardware module, whatever) is often an
Intel one.  The past releases of many Linuxen did not handle the needed
switching by the kernel to the special requirements of Intel (beyond scope
of this reply to detail, plus, brain is fuzzy), and I have often fixed it
by:

   Catch the boot process pre-kernel-boot in grub, and edit the "linux ..."
boot arguments to make 'splash" into "nosplasg".  You will never see the
"mint" logo, then.  And you may boot completely. At least you will see
messages on the console.

   Further discussion ought to be somewhere else i guess. The installer
mailing list iis for the "Fine Installer [gaw]" and boot is not
installation.

   HTH, unlikely but possible, and at least you know someone cares ;-)

-- 
*https://plus.google.com/+SörenAndersenTinoTheTwalker/
<https://plus.google.com/+S%C3%B6renAndersenTinoTheTwalker/>*
somian08@gmail.com

-- 
Are you concerned that our children are not taught right from wrong?  Why
not start by setting an example: *HONOR INDIAN TREATIES*.

-- 
“*Shikata ga nai*‟? 違(ちが)う (chigau), “Nam-Myoho-Renge-Kyo‟!
  somian08@gmail.com


-- 
*Paul Tillich: *The courage to affirm oneself must include the courage to
affirm one's own demonic depth."
*Carl G. Jung:* Such a man knows that whatever is wrong in the world is
within himself, and if he only learns to deal with his own shadow, then he
has done something real for the world.

-- 
sgiusafellowmemb:  “*I am not interested in your parroted 'nuanced
understandings' if you are not willing to hear my sincere ones.* “
Nam-Myoho-Renge-Kyo‟!
  somian08@gmail.com

**Comment by synhershko** [comment]
Thanks :)

Those edits are way beyond my comfort zone - isn't there a log being written somewhere?

FWIW, this is a desktop PC and I have an ATI graphics card (driver identifies as Radeon R9 200 series on Windows) with 2 monitors connected to it. It overrides the graphics card on the motherboard (Intel HD Graphics 4600), so yeah issues with the graphics card sound likely.

**Comment by somian** [comment]
​In reply​

On Wed, Mar 18, 2015 at 6:59 AM, Itamar Syn-Hershko <
notifications@github.com> wrote:

> FWIW, this is a desktop PC and I have an ATI graphics card (driver
> identifies as Radeon R9 200 series on Windows) with 2 monitors connected to
> it. It overrides the graphics card on the motherboard (Intel HD Graphics
> 4600), so yeah issues with the graphics card sound likely.


​I went by "camera [does something]". Sorry for the incorrect assumption.​

*​Study *the grub by visiting mint support areas.  There is no other course
I can recommend. others will probably concur.*​*

-- 
Are you concerned that our children are not taught right from wrong?  Why
not start by setting an example: *HONOR INDIAN TREATIES*.

**Comment by monsta** [comment]
> The whole installation DVD image, it boots to a black screen.

Please report it at http://blog.linuxmint.com/?p=2781. This bug tracker is for issues in LMDE installer only.
