### ISSUE TITLE
Installer leaves some system directories with rwxrwxr-x permissions

### ISSUE THREAD

**Issue by 0rzech** [linuxmint/live-installer#74]
Installer leaves some system directories with rwxrwxr-x permissions.

OS: LMDE2 Cinnamon 64-bit, 2015-03 installation disc

Repro:
1. Install system using Expert Mode
2. Execute
`ls -al | grep /target`
`ls -al | grep /target/etc`
`ls -al | grep /target/lib`

Result:
`/etc`, `/lib`, `/etc/live`, `/etc/skel`, `/lib/live` have `rwxrwxr-x` permissions.

Expected result:
`/etc`, `/lib`, `/etc/live`, `/etc/skel`, `/lib/live` should have `rwxr-xr-x` permissions.

Reproducibility:
Always.

**Comment by porzechowski** [comment]
It looks like installer does it's job well and it's just all about filesystem.squashfs contents' permissions. At least according to [line 44](https://github.com/linuxmint/live-installer/blob/2015.09.03/usr/lib/live-installer/installer.py#L44), [line 95](https://github.com/linuxmint/live-installer/blob/2015.09.03/usr/lib/live-installer/installer.py#L95), [line 176](https://github.com/linuxmint/live-installer/blob/master/usr/lib/live-installer/installer.py#L176), [line 177](https://github.com/linuxmint/live-installer/blob/master/usr/lib/live-installer/installer.py#L177) and [line 211](https://github.com/linuxmint/live-installer/blob/master/usr/lib/live-installer/installer.py#L211) in [installer.py](https://github.com/linuxmint/live-installer/blob/2015.09.03/usr/lib/live-installer/installer.py) file.

**Comment by clefebvre** [comment]
Closed following monsta's tests.
