### ISSUE TITLE
Bad translation for advanced partitioning (German)

### ISSUE THREAD

**Issue by tinxx** [linuxmint/live-installer#75]
Installing LMDE2 via the latest ISO image 'lmde-2-201503-cinnamon-64bit.iso' I stumbled upon an irritating translation error.

The German info suggests to mount target file system at '/Ziel' (German for target) while '/target' is still anticipated by the installation process.

**Comment by monsta** [comment]
Translations should be changed at https://translations.launchpad.net/linuxmint/latest/+pots/live-installer.
