### ISSUE TITLE
LMDE 2 Error message

### ISSUE THREAD

**Issue by cpatrick08** [linuxmint/live-installer#76]
I am trying to Dual boot LMDE2 from USB that I made in Windows 10 Pro 64 bit. I installed btrfs-tools from live session to be able to install the / partition with BTRFS. I get following error message during install [Errno 21] Is a directory: '/target/usr/share/bug/systemd' I've tried it with two USB flash drives and with rufus and cywgin and get same error message. Re-downloaded the ISO and still get same problem.

**Comment by cpatrick08** [comment]
I've posted forums post for this problem http://forums.linuxmint.com/viewtopic.php?f=237&t=213771

**Comment by monsta** [comment]
Looks like btrfs support isn't good here...
There's also this bug report: https://bugs.launchpad.net/bugs/1547883

**Comment by monsta** [comment]
Btrfs support is added in LMDE 4 in the manual partitioning mode, though `/@` and `/@home` subvolumes must be on different partitions (see the [release notes](https://linuxmint.com/rel_debbie.php)). This issue might be addressed in LMDE 5.
