### ISSUE TITLE
setting bootloader on GPT drive makes it crash on grub install

### ISSUE THREAD

**Issue by ThaChillera** [linuxmint/live-installer#83]
setting bootloader to install on a gpt drive (lets say in this case it's /dev/sda), requires it to either have an ESP for UEFI boot or BIOS Boot sector for legacy boot. if you don't have the correct one, the installer will crash with the message:

"the 'grub-efi-amd64-signed' package failed to install into /target/".

my forum posts about it:

https://forums.linuxmint.com/viewtopic.php?f=46&t=242324&p=1309911#p1309911

**Comment by clefebvre** [comment]
This is off-topic, it relates to ubiquity, not live-installer (LMDE).
