### ISSUE TITLE
Grammatical error in Live Installer.

### ISSUE THREAD

**Issue by PrinceShaji** [linuxmint/live-installer#84]
In the window where the installer asks whether or not to install 3rd party drivers, it says 

> This software is subject to license terms included with its documentation. Some is proprietary.

It should be "Some **are** proprietary." because it refer to multiple softwares, and thus it's not singular. 

This is not such a big deal, but it was bugging me ever since I saw it. It'll be nice if someone could fix it.

Thanks.

**Note:** I tried to fix it and make a pull request, but could not find the file.

[screenshot]
![preparing-to-install-linux-mint-18](https://user-images.githubusercontent.com/22243569/27144279-bec3cf26-5120-11e7-9be7-1d9b1cb7b5b6.png)

**Comment by kernc** [comment]
> but could not find the file.

Because this live-installer is only used in LMDE. Default Linux Mint installer is Ubiquity, repo here: https://github.com/linuxmint/ubiquity

**Comment by PrinceShaji** [comment]
Okay. Thanks.
