### ISSUE TITLE
lmde(2) *bit cinnamon+mate : mixed language content displayed during manual partitioning

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/live-installer#85]
installing new lmde(2) (qemu/kvm-vm) with english/us gui  and german keyboard (timezone) selected
When performing manual partitioning the window show's  mixed english/german content  (some buttons are labeled german).

Affects 32bit and 64bit  + cinnamon and mate (screenshot) -versions.

expected: language should be according the selected gui-localisation.

![screenshot_lmde-2-mate-32bit-language-mixed-up_2017-07-15_01 53 59](https://user-images.githubusercontent.com/29999282/28236202-3c6bc1a8-690f-11e7-973c-6d620a535055.png)

**Comment by clefebvre** [comment]
Fixed in LMDE 3.
