### ISSUE TITLE
Don't remove GParted after system installation

### ISSUE THREAD

**Issue by Alkaris** [linuxmint/live-installer#86]
One of the most useful and best disk manager GParted is a very useful utility, and it shouldn't be removed after system installation. It's included in the Live USB, so it's only natural that people would want to keep it after they've just installed their new system. Just seems counter intuitive to remove something as useful as that from a fresh install thats included by default in a Live USB installer.

I want to speak on behalf of some community people on Linux Mint (https://community.linuxmint.com/idea/view/4591) who brought this up more than 4 years ago. As Linux Mint is a modern desktop I wouldn't expect to see disk utilities like GParted to be excluded from a fresh install, which has been missing or not even included at all. I'd like to see this as a featured request implemented for future live installers.

**Comment by xenopeek** [comment]
Many thanks for contributing to Linux Mint. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by kernc** [comment]
Wow, that policy is so bollocks and counter _open_-source I can't even.

> It might lead to an implementation, it might lead to a design discussion within the team, it might be planned for a particular release and put on the roadmap, it might lead to nothing at all, or it might stick in people’s minds as something they could improve later on.

@xenopeek Might you, perhaps, shed light on which of these resolutions was chosen, if any?
