### ISSUE TITLE
Replace firefox with chromium-browser for PC with less than 2Gb RAM.

### ISSUE THREAD

**Issue by VasoVV** [linuxmint/live-installer#90]
Yesterday I've installed Linux Mint Mate 19 to old laptop with **1Gb RAM**. Desktop environment is pretty fast, but after launching firefox it completely hanged. Just one tab with youtube in a few seconds drop the system to deep swaping.
Then I've installed chromium-browser and have played youtube video more than two hours. And swap stayed almost clear.
I think that Linux Mint installer have to install a chromium-browser instead of firefox when the system has a lack of memory.
I'm a firefox fan, but here is no another solution except this one.

**Comment by xenopeek** [comment]
Thanks for contributing. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
