### ISSUE TITLE
Force UEFI Installation bug

### ISSUE THREAD

**Issue by goldstar611** [linuxmint/live-installer#91]
This bug report affects both OEM installs and normal installs.

### How to reproduce:
1. Boot a UEFI-enabled (WITH SECURE BOOT ENABLED) computer with a live usb
2. At the screen that asks if you want to perform "Erase disk and install" or "..." or "Something else" and you choose something else
3. Remove all partitions from target disk (/dev/sda)
4. Add a new partition that doesn't completely fill the disk (Filesystem = ext4 and Mountpoint = /)
5. Add a new partition to fill the rest of disk (Filesystem = swaparea)
6. Click Install Now
7. Notice that the dialog box advances to the "Where are you?" screen
8. Notice the modal dialog "Force UEFI installation?" that cannot be closed via X button, Continue button nor Go Back button.

![image](https://user-images.githubusercontent.com/13027044/44292939-6d9d3180-a24d-11e8-9dfe-f025a9ce86e8.png)

**Comment by goldstar611** [comment]
Actually, secure boot status does not matter. If you wait too long on the modal dialog, the "Where are you?" screen appears.

**Comment by kernc** [comment]
Judging by the timezone selection dialog from the attached screenshot, this is not from LMDE's live-insaller, but from a ubiquity-derived installer, i.e. here: https://github.com/linuxmint/ubiquity or here: https://bugs.launchpad.net/ubuntu/+source/ubiquity.

**Comment by goldstar611** [comment]
You are correct. There are many many instances of ubiquity in the logs. Also I found [this forum post](https://forums.linuxmint.com/viewtopic.php?t=273058) in the Newbie Section regarding an UEFI installation issue so I'm going to close this issue since I got LM19 installed finally.
