### ISSUE TITLE
Installer assumes multi boot systems are single drive systems.

### ISSUE THREAD

**Issue by mark4th** [linuxmint/live-installer#93]
I am attempting to install Mint 19 onto a laptop system that already has two installed operating systems.  /dev/sda has windows and /dev/sdb has gentoo.  I also have home on /dev/sdc and /home/data on /dev/sdd. 
What I seek to do here is to obliterate /dev/sdb and use the entire drive for mint.  I also want the entire drive to be encrypted (not encrypting during the install is absolutely NOT an option).  
If I select "whole drive" the installer does not give me any indication as to WHICH whole drive it is going to select and selecting /dev/sda would be a MAJOR catastrophic event.  
If i select "something else" then I can select /dev/sdb but the option to encrypt the target is grayed out and this again, is absolutely NOT an option.
This installer should offer the option to select exactly WHICH drive is going to be obliterated when "whole drive" is selected but it does not do so.  Therefore I can not trust this installer to not blow away my windows drive.  
What the installer needs is a "Whole drive, along side" option where the user gets to select exactly which drive gets blown away.  
I will never trust (and neither should anyone else) any Linux system that "knows better than ME" what I want or "how things should be done".  If the installer does not give me prior knowledge of what it is about to do ***AND*** offer me a means of correcting it in the event that it selects something stupid then.... said installer can not be trusted one iota.  

Please fix kthxbai :)

**Comment by clefebvre** [comment]
Please suggest this upstream to ubiquity on Launchpad. This repository here is for live-installer (the LMDE installer).
