### ISSUE TITLE
Installer should inform that you can select which disk to erase in the next step

### ISSUE THREAD

**Issue by ipimpat** [linuxmint/live-installer#97]
I have a small enhancement proposal for the installer wizard regarding the "Installation type" step.

The text below the "Erase disk and Install Linux Mint" should inform the user that the target disk can be chosen in the next step.

Both Windows 7 and 10 installers gives similar information to user:

Screenshots of Windows installer:

Windows 7: https://www.sevenforums.com/attachments/tutorials/2439d1231630451-clean-install-windows-7-a-step6.jpg
Windows 10: https://i2.wp.com/techverse.net/wp-content/uploads/2015/09/13.jpg?w=1280&ssl=1

I raise this issue after a discussion on an internet forum. A guy wrote that he had done all of the partitioning manually, because he wanted to be sure a certain target disk was used and didn't know/had not understood, that the "Erase disk and Install Linux Mint" option would offer him to select which disk to erase and create a standard layout on, when proceeding to the next step.

**Comment by ipimpat** [comment]
What I mean by "smiliar information" is that the Windows installer tells you "that you can do something with disks" in the next step.

So I think that more information could be added so the user knows that this option will do everything for you, but you will of course be asked to decide on target disk.

**Comment by clefebvre** [comment]
This relates to Ubiquity.
