### ISSUE TITLE
System doesn't boot after second reboot after installation.

### ISSUE THREAD

**Issue by damian101** [linuxmint/live-installer#98]
I installed it on an EFI system with ESP mounted to /boot/efi and a Btrfs root partition.
After installation I rebooted and everything looked fine, only Timeshift didn't work, I guess the installer didn't install the system on @ Btrfs subvolume like Calamares and many other installers do. That should be changed.
Then after a second reboot my system couldn't boot anymore which is really strange.
I tried nstalling LMDE a second time (on Btrfs again) and the same thing happened again.

**Comment by monsta** [comment]
Btrfs support is added in LMDE 4 in the manual partitioning mode, though `/@` and `/@home` subvolumes must be on different partitions (see the [release notes](https://linuxmint.com/rel_debbie.php)). This issue might be addressed in LMDE 5.
